#!/usr/bin/env python3
"""Generate anchor-point regression checkpoints for every FR curve (#18).

For each ``data/<slug>/frequency-response*.csv`` this picks 3-5 feature/reference
anchor frequencies and snapshots the curve value there via log-f interpolation,
writing ``data/<slug>/anchors.yaml``.

What this is (honest framing, see issue #18 diagnosis):
  The ``expected_db`` values are a *golden snapshot* of the already
  overlay-verified CSVs — NOT an independent re-reading of the vendor chart.
  The one-time ground-truth check happened at ingest (``overlay_verify.py``,
  recorded in each meta's ``verification`` field). The committed anchor test
  (``digitizer/test/data-anchors.test.js``) re-runs the *same* interpolation and
  fails when a value drifts past tolerance. Its job is regression detection —
  freeze the verified state, catch value corruption (typo, script bug, CRLF,
  wrong-mic data) — which is the strongest facts-only net possible without
  committing the copyrighted ground-truth image.

Consistency invariant: ``expected_db`` is computed by interpolating at the
*final rounded* anchor frequency with the identical log-f interpolation the JS
test uses. So when a CSV is unchanged the test's deviation is ~0 (only the 2-dp
rounding of ``expected_db``, <=~0.005 dB); tolerance is pure headroom for future
legitimate re-tracing.

This is a one-time / regenerate-on-review generator, not a CI dependency.
Run from anywhere: ``python3 scripts/gen_anchors.py`` (add ``--check`` to verify
the committed anchors still match the CSVs without rewriting).
"""
from __future__ import annotations

import glob
import math
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(REPO, "data")

# Round reference checkpoints (mid first), used as fallbacks after the shape
# features so even a near-flat curve still gets >=3 well-spread anchors.
REF_FREQS_HZ = [1000, 100, 10000]
TOL_DB = 0.5
MIN_LOG_SEP = 0.03      # decades; drop anchors closer than ~7% in freq (redundant checkpoints)
MAX_ANCHORS = 5         # cap; priority order keeps shape features over extra references


def read_curve(path):
    """Return ascending [(freq_hz, level_db), ...] from a freq-response CSV."""
    pts = []
    with open(path, "r", encoding="utf-8") as f:
        header = f.readline().strip()
        if header != "freq_hz,level_db":
            raise ValueError(f"{path}: unexpected header {header!r}")
        for line in f:
            line = line.strip()
            if not line:
                continue
            a, b = line.split(",")
            pts.append((float(a), float(b)))
    if len(pts) < 2:
        raise ValueError(f"{path}: needs >=2 points")
    return pts


def interp_logf(pts, freq):
    """Log-frequency linear interpolation; clamps outside the measured range."""
    if freq <= pts[0][0]:
        return pts[0][1]
    if freq >= pts[-1][0]:
        return pts[-1][1]
    lf = math.log10(freq)
    for i in range(1, len(pts)):
        f0, d0 = pts[i - 1]
        f1, d1 = pts[i]
        if freq <= f1:
            t = (lf - math.log10(f0)) / (math.log10(f1) - math.log10(f0))
            return d0 + t * (d1 - d0)
    return pts[-1][1]


def select_anchor_freqs(pts):
    """Feature + reference frequencies that capture the curve's shape.

    Endpoints (range guards) + global max (presence peak, the curve's 'face') +
    global min (deepest notch/rolloff), then round mid/low/high references as
    fallbacks. Candidates are taken in priority order and any within MIN_LOG_SEP
    decades of an already-accepted anchor is dropped — so a monotonic tail whose
    global min sits at an endpoint collapses away, while a near-flat curve still
    fills up to >=3 via the references. Capped at MAX_ANCHORS, features first.
    """
    fmin, fmax = pts[0][0], pts[-1][0]
    gmax = max(pts, key=lambda p: p[1])
    gmin = min(pts, key=lambda p: p[1])
    # Priority order: range guards + shape features first, references last.
    cands = [fmin, fmax, gmax[0], gmin[0]]
    cands += [float(rf) for rf in REF_FREQS_HZ if fmin < rf < fmax]
    accepted = []
    for fr in cands:
        r = round(fr, 1)
        if any(abs(math.log10(r) - math.log10(a)) < MIN_LOG_SEP for a in accepted):
            continue
        accepted.append(r)
        if len(accepted) >= MAX_ANCHORS:
            break
    return sorted(accepted)


def build_anchor_block(curve_file, pts):
    freqs = select_anchor_freqs(pts)
    lines = [f"  - file: {curve_file}", "    points:"]
    for fr in freqs:
        db = round(interp_logf(pts, fr), 2)
        lines.append(
            f"      - {{ freq_hz: {fr:g}, expected_db: {db:g}, tol_db: {TOL_DB:g} }}"
        )
    return "\n".join(lines)


HEADER = """\
# Anchor-point regression checkpoints (#18) — auto-generated by scripts/gen_anchors.py.
# Golden snapshot of the overlay-verified curve at feature/reference frequencies:
#   expected_db = log-f interpolation of the verified CSV; tol_db = regression tolerance.
# The test digitizer/test/data-anchors.test.js re-checks these against the CSVs on every
# `node --test` run and fails when a value drifts past tol — catching value corruption
# without needing the copyrighted vendor chart. Regenerate after a legitimate re-trace:
#   python3 scripts/gen_anchors.py
"""


def dirs_with_fr():
    out = []
    for d in sorted(os.listdir(DATA)):
        dp = os.path.join(DATA, d)
        if not os.path.isdir(dp):
            continue
        fr = sorted(glob.glob(os.path.join(dp, "frequency-response*.csv")))
        if fr:
            out.append((d, dp, fr))
    return out


def render(dp_fr):
    _d, _dp, fr_files = dp_fr
    blocks = []
    for csvp in fr_files:
        pts = read_curve(csvp)
        blocks.append(build_anchor_block(os.path.basename(csvp), pts))
    return HEADER + "curves:\n" + "\n".join(blocks) + "\n"


def main(argv):
    check = "--check" in argv
    total_curves = total_points = 0
    mismatches = []
    for d, dp, fr_files in dirs_with_fr():
        content = render((d, dp, fr_files))
        total_curves += len(fr_files)
        total_points += content.count("freq_hz:")
        path = os.path.join(dp, "anchors.yaml")
        if check:
            existing = ""
            if os.path.exists(path):
                with open(path, "r", encoding="utf-8") as f:
                    existing = f.read()
            if existing != content:
                mismatches.append(d)
        else:
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
    n_dirs = len(dirs_with_fr())
    if check:
        if mismatches:
            print(f"CHECK FAIL: {len(mismatches)} anchors.yaml out of sync: {', '.join(mismatches)}")
            return 1
        print(f"CHECK OK: {n_dirs} dirs, {total_curves} curves, {total_points} anchor points in sync")
        return 0
    print(f"Wrote anchors.yaml for {n_dirs} dirs, {total_curves} curves, {total_points} anchor points")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
